services:
  jupyter-tensorflow-notebook:
    image: predict/heartdisease
    build:
      context: .
    ports:
      - "${EXTERNAL_PORT:-8888}:8888"
    volumes:
      - ./:/app
    env_file:
      - ./jupyter-config/.env
    restart: unless-stopped
    profiles: ["local-default"]